[tools]
uv = "latest"
actionlint = "1.7.7"
action-validator = "0.6.0"
markdownlint-cli2 = "0.17.2"
yamlfmt = "0.16.0"
typos = "1.30.2"
yamllint = "1.37.0"
pre-commit = "4.1.0"
taplo = "0.9.3"


[tasks."style:lint"]
description = "Linting"
run = """
mise exec yamllint -- yamllint .
mise exec actionlint -- actionlint
mise exec action-validator -- action-validator
mise exec markdownlint-cli2 -- markdownlint-cli2 .
mise exec taplo -- taplo lint pyproject.toml
mise exec typos -- typos .
"""


[tasks."style:format"]
description = "Run the formatters"
run = """
mise exec yamlfmt -- yamlfmt .
mise exec taplo -- taplo format .
"""


[tasks."test"]
description = "Run the tests"
run = "uv run pytest tests"


[tasks."test:cov"]
description = "Run the tests with coverage"
run = "uv run coverage run -m pytest tests"


[tasks."test:cov:report"]
description = "Run the tests with coverage and generate report"
run = "uv run coverage combine && uv run coverage report"
