[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "opinionated-mixins"
dynamic = ["version"]
description = 'Opinionated set of mixins. Implemented in Pydantic, SQLAlchemy, MongoEngine, ODMantic, etc.'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [{ name = "Hasan Sezer Taşan", email = "hasansezertasan@gmail.com" }]
classifiers = [
  "Development Status :: 1 - Planning",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Typing :: Typed",
  'Environment :: Web Environment',
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: 3.13',
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []


[dependency-groups]
test = [
  "sqlalchemy",
  "mongoengine",
  "odmantic",
  "beanie",
  "wtforms",
  "pydantic[email]",
  "coverage[toml]>=6.5",
  "pytest>=8.3.4",
  "pre-commit >=2.20.0, <4.0.0",
  "mypy>=1.0.0",
  "ruff==0.11.7",
  "sqlalchemy-stubs>=0.4",
  "types-WTForms>=3.1",
]

[project.urls]
Documentation = "https://github.com/hasansezertasan/opinionated-mixins#readme"
Issues = "https://github.com/hasansezertasan/opinionated-mixins/issues"
Source = "https://github.com/hasansezertasan/opinionated-mixins"

[tool.hatch.version]
path = "src/opinionated_mixins/__about__.py"

[tool.hatch.envs.ci]
test = [
  "sqlalchemy",
  "mongoengine",
  "odmantic",
  "beanie",
  "wtforms",
  "pydantic[email]",
  "coverage[toml]>=6.5",
  "pytest>=8.3.4",
  "pre-commit >=2.20.0, <4.0.0",
  "mypy>=1.0.0",
  "ruff==0.11.7",
  "sqlalchemy-stubs>=0.4",
  "types-WTForms>=3.1",
]
[tool.hatch.envs.ci.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = ["- coverage combine", "coverage report"]
cov = ["test-cov", "cov-report"]
pre = "pre-commit run --all-files --hook-stage manual --show-diff-on-failure"
typing = "mypy --install-types --non-interactive {args:src/opinionated_mixins}"
style = ["ruff check {args:.}"]
format = ["ruff format {args:.}"]
all = ["typing", "style", "format"]
# [[tool.hatch.envs.ci.matrix]]
# python = ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]


[tool.ruff]
extend-exclude = [
  ".ipynb_checkpoints",
  ".pyenv",
  ".pytest_cache",
  ".vscode",
  "build",
  "site-packages",
  "alembic",
  "migrations",
]
target-version = "py38"
show-fixes = true
extend-include = ["*.ipynb"]
fix = true


[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM",  # flake8-commas
  "FA",   # flake8-future-annotations
  "ISC",  # flake8-implicit-str-concat
  "INP",  # flake8-no-pep420
  "PGH",  # pygrep-hooks
  "PL",   # Pylint
  "E501", # line too long, handled by black
  "E402", # module level import not at top of file
  "W191", # indentation contains tabs
  "F401", # imported but unused
]
preview = true


[tool.ruff.lint.flake8-copyright]
author = "Hasan Sezer Taşan <hasansezertasan@gmail.com>"


[tool.ruff.lint.pydocstyle]
convention = "google"


[tool.ruff.lint.isort]
known-third-party = ["opinionated_mixins"]


[tool.ruff.format]
docstring-code-format = true


[tool.mypy]
python_version = "3.8"
show_column_numbers = true
ignore_missing_imports = true


[tool.coverage.run]
source_pkgs = ["opinionated_mixins", "tests"]
branch = true
parallel = true
omit = ["src/opinionated_mixins/__about__.py"]


[tool.coverage.paths]
opinionated_mixins = [
  "src/opinionated_mixins",
  "*/opinionated-mixins/src/opinionated_mixins",
]
tests = ["tests", "*/opinionated-mixins/tests"]


[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
